import React from 'react';
import { Form } from 'react-bootstrap';
import { InputNewTodo } from '../InputNewTodo';
import UserSelect from '../UserSelect';
import { connect } from 'react-redux';
import styles from './MainApp.module.css';

// let's move this type in separate folder and file types.ts or models.ts
type Todo = {
    title: string,
    // let's rename it to userId
    user?: number,
    isDone: boolean,
}

type MainAppProps = {
    todos: Todo[],
    addTodo: (t: Todo) => void,
    changeTodo: (todos: Todo[]) => void,
}
type MainAppState = {
    todoTitle: string
};

// Let's use functional component, it's simple js functions - version of React allow us to do it
// Solving problems:
// - we can use useState for state

// Let's name it correctly - App
class Index extends React.Component<MainAppProps, MainAppState> {
    constructor(props: MainAppProps) {
        super(props);
        this.state = { todoTitle: '' }
    }

    handleTodoTitle = (todoTitle: string) => {
        this.setState({ todoTitle })
    }

    // Let's not writing any. We Todo type, so let's import it from other file
    handleSubmitTodo = (todo: any) => {
        this.props.addTodo(todo)
    }

    render() {
        const { todoTitle } = this.state;

        // we can calculate this value dependce on all todos
        // and move it useMemo to not re-calculate after every render
        window.allTodosIsDone = true;

        this.props.todos.map(t => {
            if (!t.isDone) {
                // please use setState method from useState as desсribed above
                window.allTodosIsDone = false
            } else {
                window.allTodosIsDone = true
            }
        });

        return (
            <div>
                {/* Let's use some kind of picture inctead, we don't need this element without any form/input functionality */}
                {/* I mean without user interaction */}
                <Form.Check type="checkbox" label="all todos is done!" checked={window.allTodosIsDone}/>

                <hr/>

                <InputNewTodo todoTitle={todoTitle} onChange={this.handleTodoTitle} onSubmit={this.handleSubmitTodo}/>
            
                {/* Let's set set key here */}
                {this.props.todos.map((t, idx) => (
                    <div className={styles.todo} >
                        {t.title}
                        <UserSelect user={t.user} idx={idx}/>

                        {/* Please move all props and attrs to new row */}
                        {/* also please move onChange func to method of component */}
                        <Form.Check
                            style={{ marginTop: -8, marginLeft: 5 }}
                            type="checkbox" checked={t.isDone} onChange={(e) => {
                            const changedTodos = this.props.todos.map((t, index) => {
                                const res = { ...t }
                                if (index == idx) {
                                    res.isDone = !t.isDone;
                                }
                                return res;

                            })
                            this.props.changeTodo(changedTodos)

                        }}
                        />
                    </div>
                ))}
            </div>
        );
    }
}

// We do not need this kind of connection
// I describe idea of slices and RTKQueries here and in store.ts file
// All we need is to export action generated by redux toolkit sliced and query functionality 
// (from our custom hook) And use it - call it
// Also it give us isLoading functioonality in case of RKTQuery

export default connect(
    (state) => ({}),
    (dispatch) => ({
        addTodo: (todo: any) => {
            dispatch({type: 'ADD_TODO', payload: todo});
        },
        changeTodo: (todos: any) => dispatch({type: 'CHANGE_TODOS', payload: todos}),
        removeTodo: (index: number) => dispatch({type: 'REMOVE_TODOS', payload: index}),
    })

)(Index);
